export let historydata = [
  {
    S_No: 1,
    Employee_Name: 'Employee1',
    Employee_ID: 'E001',
    Current_Role: 'Solution Devloper',
    Activity: 'Project Modified',
    Activity_On: '09-10-2023, 12:00 PM',
    Activity_By: 'Navneeth Vijaynath',
    Description: 'Project Summary modified',
  },
  {
    S_No: 2,
    Employee_Name: 'Employee2',
    Employee_ID: 'E002',
    Current_Role: 'Solution Devloper',
    Activity: 'Metronics V1',
    Activity_On: '09-10-2023, 12:00 PM',
    Activity_By: 'Alia Jackson',
    Description: 'Project Summary modified',
  },
  {
    S_No: 3,
    Employee_Name: 'Employee3',
    Employee_ID: 'E003',
    Current_Role: 'Solution Devloper',
    Activity: 'Layers V5',
    Activity_On: '09-10-2023, 12:00 PM',
    Activity_By: 'Navneeth Vijaynath',
    Description: 'Project Summary modified',
  },
  {
    S_No: 4,
    Employee_Name: 'Employee4',
    Employee_ID: 'E004',
    Current_Role: 'Solution Devloper',
    Activity: 'Quadwave V2',
    Activity_On: '09-10-2023, 12:00 PM',
    Activity_By: 'Alia Jackson',
    Description: 'Project Summary modified',
  },
  {
    S_No: 5,
    Employee_Name: 'Employee5',
    Employee_ID: 'E005',
    Current_Role: 'Solution Devloper',
    Activity: 'Project Modified',
    Activity_On: '09-10-2023, 12:00 PM',
    Activity_By: 'Navneeth Vijaynath',
    Description: 'Project Summary modified',
  },
  {
    S_No: 6,
    Employee_Name: 'Employee6',
    Employee_ID: 'E006',
    Current_Role: 'Solution Devloper',
    Activity: 'Project Modified',
    Activity_On: '09-10-2023, 12:00 PM',
    Activity_By: 'Navneeth Vijaynath',
    Description: 'Project Summary modified',
  },
  {
    S_No: 7,
    Employee_Name: 'Employee7',
    Employee_ID: 'E007',
    Current_Role: 'Solution Devloper',
    Employee_Name: 'Employee',
    Employee_ID: 'E001',
    Current_Role: 'Solution Devloper',
    Activity: 'Project Modified',
    Activity_On: '09-10-2023, 12:00 PM',
    Activity_By: 'Navneeth Vijaynath',
    Description: 'Project Summary modified',
  },
  {
    S_No: 8,
    Employee_Name: 'Employee8',
    Employee_ID: 'E008',
    Current_Role: 'Solution Devloper',
    Activity: 'Project Modified',
    Activity_On: '09-10-2023, 12:00 PM',
    Activity_By: 'Navneeth Vijaynath',
    Description: 'Project Summary modified',
  },
  {
    S_No: 9,
    Employee_Name: 'Employee9',
    Employee_ID: 'E009',
    Current_Role: 'Solution Devloper',
    Activity: 'Project Modified',
    Activity_On: '09-10-2023, 12:00 PM',
    Activity_By: 'Navneeth Vijaynath',
    Description: 'Project Summary modified',
  },
  {
    S_No: 10,
    Employee_Name: 'Employee10',
    Employee_ID: 'E010',
    Current_Role: 'Solution Devloper',
    Activity: 'Project Modified',
    Activity_On: '09-10-2023, 12:00 PM',
    Activity_By: 'Navneeth Vijaynath',
    Description: 'Project Summary modified',
  },
]
