export const FETCH_TECHNOLOGY_SUCCESS = 'FETCH_TECHNOLOGY_SUCCESS';
export const ADD_TECHNOLOGY_SUCCESS = 'ADD_TECHNOLOGY_SUCCESS';
export const UPDATE_TECHNOLOGY_SUCCESS = 'UPDATE_TECHNOLOGY_SUCCESS';
export const DELETE_TECHNOLOGY_SUCCESS = 'DELETE_TECHNOLOGY_SUCCESS';